# Generated by Django 2.0.3 on 2018-03-23 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_pomodoros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pomodoros',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
